export default {
  Login: 'Login',
  Splash: 'Splash',
  DetailScreen: 'DetailScreen',
  HomeScreen: 'HomeScreen',
  ProfileScreen: 'ProfileScreen',
  MainBottomTab: 'MainBottomTab',
  AuthorScreen: 'AuthorScreen',
  TagsScreen: 'TagsScreen',
  RandomQuoteScreen: 'RandomQuoteScreen',
  QuoteByAuthorScreen: 'QuoteByAuthorScreen',
  QuoteByTagScreen: 'QuoteByTagScreen',
  TagsDetailScreen: 'TagsDetailScreen',
  QuoteDetailsScreen: 'QuoteDetailsScreen',
}
